### ISSUE TITLE
Rollback operation for a branch of repositories

### ISSUE THREAD

**Issue by narugo1992** [huggingface/huggingface_hub#2406]
We developed a huggingface_hub wrapping library [hfutils](https://github.com/deepghs/hfutils).

When i tried to use function [upload_directory_as_directory](https://deepghs.github.io/hfutils/main/api_doc/operate/upload.html#upload-directory-as-directory) to upload a large directory tree (containing 3k+ files, 99% of then smaller than 0.5mb) to huggingface_hub, get http 413 error which may means too many files in one commit.

So i think the solution is to upload all these files with several commits. But another problem is, i have to make sure the consisteny of the repository, the half-completed uploading may cause unexpected error to workflow. Based on this requirements, i prefer to execute a rollback operation when there are errors during these several commits.

But i cannot find a method implemented this rollback operation. The only solution for rolling back a hf repository is using `git clone`, `git reset` and `git push -f`. I will implement this in hfutils library. But can we have a better approach to rollback a repository, i mean force reset the latest commit of a branch to another given commit.

**Comment by narugo1992** [comment]
my implement, based on git operations: https://github.com/deepghs/hfutils/pull/27

**Comment by Wauplin** [comment]
Hi @narugo1992, by "rollback" do you mean erasing the commit history to remove the latest one? If yes, I don't think we'll ever support it official since it's usually bad practice to rewrite a git history (you loose backup + it might conflict with local clones). Something that could be done is a revert commit but I'm not sure there is enough demand for it.

A cleaner solution to your problem could be to upload files to a PR revision and once everything is uploaded, make a merge commit. This can entirely be done using `huggingface_hub`'s HTTP methods without requiring to git clone the repo locally -which is usually a no-go on large repos-.

Also to mention, we are currently working on a PR (https://github.com/huggingface/huggingface_hub/pull/2254) to add a command that can upload arbitrary large folders a repo on the Hub. It handles small or big files, with a retry mechanism, with multithreading and chunks the commits to be sure not to reach the threshold where commits are failing.

**Comment by narugo1992** [comment]
> Hi @narugo1992, by "rollback" do you mean erasing the commit history to remove the latest one? If yes, I don't think we'll ever support it official since it's usually bad practice to rewrite a git history (you loose backup + it might conflict with local clones). Something that could be done is a revert commit but I'm not sure there is enough demand for it.

Using PR is indeed a good approach for uploading large amounts of data at once. 

However, I have another practical use case. When it comes to long-term maintenance of a dataset, rather than a one-time bulk upload, if there is an anomaly, such as data format errors, system bugs, etc., it is necessary to erase the corrupted data and rollback to the last normal commit. 

Using PR is not suitable for long-term maintenance. Long-term data maintenance often involves uploading several files and modifying parquet data files at one commit hourly. During this process, unless data anomalies are discovered, no human will participate and approve the prs.

Therefore, I have implemented a rollback operation based on git operations.

**Comment by Wauplin** [comment]
I understand your concern. Thanks for sharing details. As explained above, I still don't think we'll add such a feature officially. I'll close this issue as "won't fix" but happy to re-open it if more community members request it. In the meantime, I'm encouraging users to try out the tool you've shared :)
