### ISSUE TITLE
Allow uploading large files via the web UI

### ISSUE THREAD

**Issue by josephrocca** [huggingface/huggingface_hub#555]
**Is your feature request related to a problem? Please describe.**
I tried to upload a 13GB dataset file (for [this repo](https://huggingface.co/datasets/rocca/sims4-faces)), and after waiting a couple of hours for it to upload, it gave a "Payload too large" error.

**Describe the solution you'd like**
I'd like to be able to upload large dataset files using the web UI.

**Describe alternatives you've considered**
I'm guessing there's some sort of command line tool for cases like this, but I'd prefer to not have to install something just to upload a file - it's bad UX. There's no fundamental technical reason why the web UI can't handle large files, so it doesn't seem like a good idea to put limits like this in place.

**Additional info**
If the team is for some reason adamant about not allowing upload of large files via the web UI, then at the very least it would be good to stop the user with an error when they pick the file, rather than after the upload is complete. I.e. check the size of the blob with JS before uploading rather than uploading and checking size on the server.

Thanks!

**Comment by LysandreJik** [comment]
cc @julien-c

**Comment by julien-c** [comment]
For @SBrandeis (and cc @Pierrci) 

I think we said we would remove the 5GB limit on file upload no? (But WDYT of keeping a 20GB limit as larger than that files aren't CDN-distributed and it's just not something that we want to support IMO)

**Comment by julien-c** [comment]
Thanks for the report @josephrocca the plan is to support file uploads up to 20GB and check the blob size client-side for files larger than 20GB.

WDYT?

**Comment by josephrocca** [comment]
Any progress on this? Just tried again, but this time I split the file into a couple of ~6GB files to be safe. This time I got a 504 error for one of them, and a 500 error for the other. I have a symmetric gigabit connection, but the uploads took 1 or 2 hours, so it seems a bit slower than it perhaps should be, and maybe that caused the 504 timeout, but I'm not sure about the 500 error. The speed issue could just be due to the fact that I'm based in Singapore.

**Comment by julien-c** [comment]
This has been implemented/shipped 20 days ago but we had server connectivity issues earlier today so maybe it was a temporary hiccup?

**Comment by josephrocca** [comment]
@julien-c I just tried again and got a 500 error when it was >80% complete (after about 40-50 minutes). I'm just uploading a 6GB tar file, and it uploads at about 2 megabytes/sec. A 600MB file uploads fine. If you can somehow simulate the 2 MB/s upload speed (devtools might alow you to do this?) then my guess is that you'd be able to replicate it. Seems like it has to do with some sort of timeout on the server-side.

**Comment by SBrandeis** [comment]
Hello @josephrocca, we fixed the underlying issue preventing uploads of large files to the Hub

You should now be able to upload files up to 20GB as stated by @julien-c earlier

**Comment by josephrocca** [comment]
@SBrandeis Hi Simon, I just tested 4 times, and it always fails after 40-50 minutes with `net::ERR_CONNECTION_CLOSED`. Here's a video of the last few seconds as it fails:

https://user-images.githubusercontent.com/1167575/152629860-58cdbd5c-3d42-49a8-8695-9ee8258a511d.mp4

Previously it would show a red error box in the upload UI, but now there's no indication of the error on the web page itself. Here's what Chrome reports in the console:

![image](https://user-images.githubusercontent.com/1167575/152629912-56b54f55-3f48-422d-bb72-8b185e08b21f.png)

As mentioned earlier, it's just a 6GB tar file. My average upload speed is about 1.5MB/s. You should be able to emulate this upload speed with Chrome's DevTools IIRC.

**Comment by josephrocca** [comment]
@SBrandeis Any progress on this? I just tried to upload a 480mb file and that gave me a error (code 500). I tried a second time and it worked. I tried the above-mentioned 6GB tar again a couple of times but it still doesn't work. So seems flaky, and maybe worse as files get larger? Can you reproduce the errors that I'm talking about, or is it working okay on your end? 

To quickly create a ~6GB tar to reproduce:
```
dd if=/dev/zero of=upload_test bs=1M count=6000
tar -cf upload_test.tar upload_test
```

And network connection throttling (to match my ~1.5 megabytes/s upload) is in Chrome DevTools:

![Screenshot from 2022-03-10 21-38-14](https://user-images.githubusercontent.com/1167575/157673440-01425576-62ea-433c-8c87-359191ef0b8c.jpg)

**Comment by SBrandeis** [comment]
Hello @josephrocca

There was indeed an issue preventing the upload of files larger than ~5GB, I'm sorry for the inconvenience

We've released a fix yesterday, and I've been able to successfully upload a 6GB file via the UI today, with network throttling to simulate a low bandwidth: https://huggingface.co/datasets/sbrandeis/test-ui-upload/tree/main

Error reporting is still meh (you have to send the whole file over the network for the browser to display the error), we're working on improving this

Please let me know if you still experience issues with web file uploads

**Comment by josephrocca** [comment]
@SBrandeis Thanks! The lack of early errors probably isn't such a big issue now that the upload limit is much higher, although I guess it would be pretty annoying to wait for several hours and get an error, for those that don't know about the limits. And I guess it is basically a one-liner to fix this - i.e. the non-minified equivalent of `if(s.size > max) showTheError()` here:

![Screenshot from 2022-03-12 12-56-55](https://user-images.githubusercontent.com/1167575/158006658-77b0d29e-9d03-4544-9365-acff866dca67.jpg)

But feel free to close this if the current state is considered good enough for now (I [see](https://github.com/huggingface/huggingface_hub/issues/497#issuecomment-1063028629) that a revamp is going to happen at some point which might make any extra work here not worth it).

**Comment by julien-c** [comment]
(for context @josephrocca on that linked comment, we're going to probably ~reimplement the LFS part of git in the browser 🤯 )

**Comment by josephrocca** [comment]
Still getting code-500 errors here and there :/ This was for a 3.5GB tar file:

![image](https://user-images.githubusercontent.com/1167575/158046784-0e261812-965a-4dff-84b0-161544c63c00.png)

Tried again and it worked the second time though. No idea what caused it, but one difference was that during the first upload I was creating other small files (e.g. readme, etc.) while it was running. I was adding the other files via the "Create a new file" (and pasting in text), not the "Upload file" button. During the second upload attempt I did not make any changes/additions to the repo. But if that were the problem, then I'd expect to have seen [this error message](https://github.com/huggingface/huggingface_hub/issues/707#issuecomment-1059886487) instead.

**Comment by julien-c** [comment]
Yes we do not support concurrent commits while uploading/committing a file through the UI

**Comment by julien-c** [comment]
> should the backend lock the repo while there's an upload in progress?

I believe @SBrandeis has a PR open to relax this requirement
